trigger:
  branches:
    include:
      - main  # Or your preferred branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'your-azure-subscription'
  terraformWorkingDirectory: '$(Build.SourcesDirectory)'  # Path to the Terraform directory
  terraformVersion: '1.3.0'  # Adjust the version as needed

steps:
- task: UseTerraform@0
  inputs:
    terraformVersion: $(terraformVersion)

- task: AzureCLI@2
  displayName: 'Authenticate with Azure'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging into Azure..."
      az account set --subscription $(azureSubscription)

- task: TerraformInstaller@0
  inputs:
    terraformVersion: $(terraformVersion)

- task: TerraformCLI@0
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    workingDirectory: $(terraformWorkingDirectory)
    command: 'init'
    backendServiceArm: $(azureSubscription)

- task: TerraformCLI@0
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    workingDirectory: $(terraformWorkingDirectory)
    command: 'plan'
    environmentServiceName: $(azureSubscription)

- task: TerraformCLI@0
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    workingDirectory: $(terraformWorkingDirectory)
    command: 'apply'
    args: '-auto-approve'
    environmentServiceName: $(azureSubscription)
